
services:
  postgres:
    image: postgres:15.3
    container_name: postgres-15-dev
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: capitalsys
    volumes:
      - ./postgres:/var/lib/postgresql/data

