services:
#  postgres:
#    container_name: postgres
#    image: postgres:15.3
#    restart: always
#    ports:
#      - "5436:5432"
#    environment:
#      POSTGRES_USER: ${DB_USERNAME} # Usando variables del .env
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
#    networks:
#      - app-network
#
  capital-app:
    build: .
    image: capital/app:latest
    container_name: capital-app
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
#    depends_on:
#      - postgres
    networks:
      - app-network

  capital-reportes:
    build:
      context: ../reportes-spring
      dockerfile: Dockerfile
    image: capital/reportes:latest
    container_name: capital-reportes
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - reportes-data:/app/jasper
    networks:
      - app-network

volumes:
  reportes-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\reportes

networks:
  app-network:
    driver: bridge
